### ISSUE TITLE
Adding cProfile (pstat) conversion 

### ISSUE THREAD

**Issue by tonybaloney** [P403n1x87/austin-python#1]
I want to use the PyCharm cProfile visualiser to view Austin-generated profiles.

It requires pstat files generated from the `pstats` stdlib module. I'm about to write that feature and submit a PR. 

If you've already written this please let me know!

**Comment by P403n1x87** [comment]
@tonybaloney I haven't written this feature and your contribution certainly is more than welcome :smiley:

**Comment by tonybaloney** [comment]
#2

**Comment by P403n1x87** [comment]
Closing as the associated PR has been closed. If there is a need for this we can re-evaluate.
