### ISSUE TITLE
austin2speedscope with child process tracking generates a bogus graph

### ISSUE THREAD

**Issue by pradyunsg** [P403n1x87/austin-python#23]
### Steps to Reproduce

1. Clone https://github.com/pypa/pip and checkout `b551c09c4ef21c675a46504b4883d897b4b82f33`
2. Create a virtual environment.
3. `pip install -e .`
4. `sudo austin -C -o profile.austin python -m pip install --dry-run pyrax==1.9.8`
5. `austin2speedscope profile.austin profile-austin.json`

**Expected behavior:**

A valid speedscope JSON file is generated, that renders the collected contents in a detailed flamegraph.

**Actual behavior:**

What seems like not particularly useful `Thread._bootstrap` calls.

<img width="1440" alt="Screenshot 2023-10-23 at 23 44 51" src="https://github.com/P403n1x87/austin-python/assets/3275593/1432cb2c-c00e-4d51-98c0-60bc783bd135">

Notably, the file does contain the relevant information that seems appropriate for format but it doesn't seem to be in the correct representation for speedscope to consider rendering it.

**Reproduces how often:**

100%, so far.

### Versions

```
❯ austin --version                                    
austin 3.6.0
❯ austin2speedscope --version                         
0.2.1
❯ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 13.6 (22G120)
      Kernel Version: Darwin 22.6.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: M1 MacBook Air
      User Name: Pradyun Gedam (pradyunsg)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 16 days, 7 minutes

```

### Additional Information

Relevant profile.austin file is 1.3GB.

**Comment by pradyunsg** [comment]
Turns out, the files are extremely compressible.

- [profile-austin.json.gz](https://github.com/P403n1x87/austin-python/files/13083527/profile-austin.json.gz)
- [profile.austin.gz](https://github.com/P403n1x87/austin-python/files/13083538/profile.austin.gz)

**Comment by P403n1x87** [comment]
@pradyunsg thanks for reporting this, I'll try to have a look at the attached data soon. In the meantime, may I check which version of Python is Austin being run against? 3.11 or 3.12? Looking at the speedscope attachment I can see that there are 47 profiles (one for each combination of processes, sub-interpreters and threads within them). Do they all look like the one screenshotted?

**Comment by P403n1x87** [comment]
This is the global picture that I get following the steps in the OP, but using a sampling interval of 10ms to reduce the number of samples (I have also run the command beforehand without Austin, which triggered the download of a few wheels, so this wall time profile does not include the time spent downloading those), and opening the resulting data in VS Code with the Austin extension. There seems to be only one interesting process (the parent?).

<img width="1440" alt="Screenshot 2023-10-24 at 21 09 05" src="https://github.com/P403n1x87/austin-python/assets/20231758/ca2531e1-ba4e-497f-8f4a-d524cfeb17d4">

I suspect what you are observing is this stack highlighted here with the red rectangle

<img width="1440" alt="Screenshot 2023-10-24 at 21 13 31" src="https://github.com/P403n1x87/austin-python/assets/20231758/00850c9e-e27c-4673-8729-b109f3c1b0fc">

**Comment by P403n1x87** [comment]
Confirmation that picking the "right" profile shows more "interesting" flamegraphs (left-heavy mode)

<img width="1440" alt="Screenshot 2023-10-24 at 21 21 34" src="https://github.com/P403n1x87/austin-python/assets/20231758/40d72e04-69e3-4bfd-aa62-bfcacfbf1db1">

**Comment by pradyunsg** [comment]
Python 3.11, I believe.

> Looking at the speedscope attachment I can see that there are 47 profiles (one for each combination of processes, sub-interpreters and threads within them).

Aha! This made me look around the page for a 47 and, well, now I feel dumb. TIL that I can select different profiles from the top bar on the speedscope UI. 🤦🏽

It now makes more sense why profiles is a list in the JSON schema for speedscope.

> Confirmation that picking the "right" profile shows more "interesting" flamegraphs (left-heavy mode)

Thanks a lot for taking a look at this, and sorry for what ended up being a dumb misunderstanding on my end! This data looks like it's gonna be super useful!

**Comment by P403n1x87** [comment]
> Thanks a lot for taking a look at this, and sorry for what ended up being a dumb misunderstanding on my end! This data looks like it's gonna be super useful!

No problem at all, happy to help, and glad the data looks useful! 🙂
