### ISSUE TITLE
Generated trace files cannot be converted to .json with austin2speedscope

### ISSUE THREAD

**Issue by syegulalp** [P403n1x87/austin-python#6]
### Description

Generated trace files cannot be converted to .json with austin2speedscope

### Steps to Reproduce

1. Run austin to generate trace: `.\austin -o output.austin -C py conway.py`
2. Run austin2speedscope: `austin2speedscope.exe .\output.austin output.json`

**Expected behavior:** Data should be converted into JSON

**Actual behavior:** The resulting file is almost completely empty:

```json
{"$schema": "https://www.speedscope.app/file-format-schema.json", "shared": {"frames": []}, "profiles": [], "name": "output.austin", "exporter": "Austin2Speedscope Converter 0.2.0"}
```

**Reproduces how often:** 100% of the time

### Versions

austin 3.0.0

### Additional Information

Running in a Python 3.8 venv on Microsoft Windows [Version 10.0.19043.1110]

The raw trace file is 17MB in size (not sure if that's to be expected)

**Comment by syegulalp** [comment]
[output.zip](https://github.com/P403n1x87/austin-python/files/6817277/output.zip)

Attached is a zipped copy of the Austin trace file generated.

**Comment by justus-saul** [comment]
Have you found a solution? Having the same issue on Linux right now.
